--
-- Created by IntelliJ IDEA.
-- User: shashi
-- Date: 2019-04-25
-- Time: 20:00
-- To change this template use File | Settings | File Templates.
--

--function love.conf(t)
--- -    t.window.title = "this is my first app"
---- t.window.width = 640
---- t.window.height = 480
---- t.console = true
---- t.modules.touch = false
----end